name: Makefile CI

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install cpanm
      run: sudo apt-get install cpanminus

    - name: Install modules
      run: sudo cpanm HTTP::Server::Simple::CGI File::Type Path::Class

    - name: Run test
      run: make test
